#!/usr/bin/env python
import sys
import time
import portio

r = portio.ioperm(0x62, 1, 1)
r = portio.ioperm(0x66, 1, 1)
val = int(sys.argv[1], 16)

def wait_write():
    i = 100
    print("wait")
    while (portio.inb(0x66) & 0x02) and i:
        print("-loop")
        i -= 1
        time.sleep(0.1)
    return i

def write(port, val):
    if wait_write():
        portio.outb(val, port)

write(0x66, 0x81)
write(0x62, 0x31)
write(0x62, val)


